version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/wcmcio
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ".env"
 
  redis:
    image: redis

  sidekiq:
     build: .
     volumes:
       - .:/wcmcio
     links:
       - db
       - redis
     command: bundle exec sidekiq
     env_file:
       - ".env"
