host: 'https://carbon-tool.cartodb.com'
oauth_key: '0QN2jT32Lxripd0ER6yOxwuX6XdTQKbGLrRiCOi3'
oauth_secret: 'NsglZeOQFMdHCTErKZIbtttiNOuijJYZ5KPREoew'
username: 'carbon-tool'
password: 'cCWuv2uC'
api_key: 'dd7d757da5f046dc3e4e75c73d311234c3f0399d'
