production:
  instance: https://dasboard.unepwcmc-014.vm.brightbox.net
  metrics:
    wdpa_release_downloads: 3
staging:
  instance: https://dasboard.unepwcmc-011.vm.brightbox.net
  metrics:
    wdpa_release_downloads: 3
development:
  instance: https://dasboard.unepwcmc-014.vm.brightbox.net
  metrics:
    wdpa_release_downloads: 3
