default: &default
  beta_team: "Informatics"
  slack_notification_webhook_url": "<%= ENV[SLACK_NOTIFICATION_WEBHOOK_URL] %>"

development:
  <<: *default

testing:
  <<: *default
  beta_team: "Business and Biodiversity"

staging:
  <<: *default

production:
  <<: *default
  beta_team: "Business and Biodiversity"

