default: &default
  beta_team: "Informatics"
  onedrive:
    app_id: <%= ENV["MS_APP_ID"] %>
    password: <%= ENV["MS_PASSWORD"] %>


development:
  <<: *default
  onedrive:
    app_id: <%= ENV["MS_APP_ID_DEV"] %>
    password: <%= ENV["MS_PASSWORD_DEV"] %>

testing:
  <<: *default
  beta_team: "Business and Biodiversity"

staging:
  <<: *default

production:
  <<: *default
  beta_team: "Business and Biodiversity"

