default: &default
  beta_team: "Informatics"

development:
  <<: *default

testing:
  <<: *default
  beta_team: "Business and Biodiversity"

staging:
  <<: *default

production:
  <<: *default
  beta_team: "Business and Biodiversity"

