default: &default
  beta_team: "Informatics"
  onedrive:
    app_id: <%= ENV["MS_APP_ID"] %>
    password: <%= ENV["MS_PASSWORD"] %>


development:
  <<: *default

testing:
  <<: *default
  beta_team: "Business and Biodiversity"

staging:
  <<: *default
  onedrive:
    app_id: <%= ENV["MS_APP_ID_STAGING"] %>
    password: <%= ENV["MS_PASSWORD_STAGING"] %>

production:
  <<: *default
  beta_team: "Business and Biodiversity"

